#
# $Id: build.properties,v 1.6 2007/11/07 22:27:25 clamatius Exp $

build=build
data=data
dist=dist
cppsrc=src/cpp

output.name=whichbot

whichbot.dir=addons/whichbot
waypoints.dir=${whichbot.dir}/data

distzipfile=${build}/whichbot-${version}.zip

gcc-lib=/usr/lib/gcc/i486-linux-gnu/4.1.2

